### ISSUE TITLE
Build fails on OS X without homebrew installed

### ISSUE THREAD

**Issue by seliopou** [dinosaure/overlap#1]
I was trying to install [mirage/mrmime]() and ran into some trouble while attempting to install dependencies. Specifically, this library specifies a dependency on `conf-pkg-config` which fails on a non-homebrew OS X install:

```
$ opam install bigarray-overlap
The following actions will be performed:
  ∗ install conf-pkg-config  1.1   [required by bigarray-overlap]
  ∗ install bigarray-overlap 0.1.0
===== ∗ 2 =====
Do you want to continue? [Y/n] y

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[bigarray-overlap.0.1.0] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[ERROR] The compilation of conf-pkg-config failed at "/Users/seliopou/.opam/opam-init/hooks/sandbox.sh build pkg-config --help".

#=== ERROR while compiling conf-pkg-config.1.1 ================================#
# context     2.0.4 | macos/x86_64 | ocaml-base-compiler.4.08.0 | https://opam.ocaml.org#0aafbe00
# path        ~/.opam/default/.opam-switch/build/conf-pkg-config.1.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build pkg-config --help
# exit-code   71
# env-file    ~/.opam/log/conf-pkg-config-69305-d2c37b.env
# output-file ~/.opam/log/conf-pkg-config-69305-d2c37b.out
### output ###
# sandbox-exec: execvp() of 'pkg-config' failed: No such file or directory



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build conf-pkg-config 1.1
└─ 
╶─ No changes have been performed
```

`conf-pkg-config` doesn't seem to be listed as a dependency in the OPAM file contained in this repository, but rather was added in ocaml/opam-repository@ca76e906ddf15832433a3a10652b40a3e603e371. So I pinned my local checkout and installed mrmime without any trouble.

So I'm wondering then if it's possible to setup the library's dependencies in OPAM so that on OS X installing `conf-pkg-config` isn't necessary? I was hoping to add mrmime as a dependency to a few projects and this would make that transition a lot smoother.

Thanks!

**Comment by dinosaure** [comment]
Interesting, I don't have a Mac with me but `pkg-config` is needed to get C flags required to compile artifacts for MirageOS. In other side, I try to integrate such small function into the OCaml distribution (eg. ocaml/ocaml#8618) to avoid such plumbing on my side.

I believe that as a `depopts`, it should be fine but I'm not really sure. Let me investigate on this way.

**Comment by seliopou** [comment]
For what it's worth, I don't have this issue with bigstringaf and it presumably works with other mirage libraries. I checked out some of the files related to xen and freestanding support and they differ significantly from what's in this repo. Also, the OPAM file is very different and in bigstringaf there is a META template file as well.

Maybe some of what's done in bigstringaf could be ported to this library?

**Comment by dinosaure** [comment]
Ok, I will try to make a release soon with a `js_of_ocaml` support and see what CI tell me - in your way, `conf-pkg-config` should be needed only for tests.

EDIT: `opam depext` should fix your problem otherwise.

**Comment by dinosaure** [comment]
Should be fixed with the last release of `mrmime.0.3.0` and `bigarray-overlap.0.2.0`. I hope it will help to enjoy `mrmime` :+1:.
